- CHANGELOG.md
- README.md
- filter.php
You can use {alternatename} instead of {firstname}. If {alternatename} contains a name, it will be used. Otherwise it will have the same effect as if you had used {firstname}.
> Added new tag {alternatename}.

- CHANGELOG.md
- README.md
- filter.php
Returns the City as specified in the user profile. See issue #11 .
> Added new tag {city}.

- CHANGELOG.md
- README.md
- filter.php
Returns the country as specified in the user's profile. Note that the country name will be in the user's current language. See issue #12 .
> Added new tag {country}.

- CHANGELOG.md
- README.md
- filter.php
Will be replaced by the institution name from the user's profile. For more information, see issue #19
> Added new tag {institution}.

- CHANGELOG.md
- README.md
- filter.php
This filtercode will be replaced by the department as listed in the user's profile. See issue #21 .
> Added new tag {department}.

- CHANGELOG.md
- README.md
- filter.php
- version.php
First BETA release.
Now compatible with Moodle 2.7 through 3.4.
Fixed bug with blank user profile country.
> First BETA release is compatible with Moodle 2.7 to 3.4. Bug fixes.

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- filter.php
- Added support for multiple occurences of same {if...}{/if...} tags.
- Added support for multiline spanning of {if...}{/if...} tags.
- Added useful examples of using FilterCodes in custom menus (see Usage section of documentation).
- Fixed {mycourses} and {mycoursesmenu} tags are no longer ever empty.
> New features and fixes.

- CHANGELOG.md
- README.md
- filter.php
See documentation for Contact Form for Moodle plugin.
> ReCAPTCHA is now officially supported. For use with Contact Form plugin

- README.md
- filter.php
- tests/filter_test.php
In custom user menu and custom nav menu.
> Corrected code to add to themes to enable Moodle filter codes

- db/upgrade.php
For more information, see #58 .
> Feature request: Enabled FilterCodes upgrade notification from within Moodle.

- CHANGELOG.md
- README.md
- filter.php
- version.php
These encoded versions of {courseid} and {userid} can be helpful when dealing with escaped URLs.
> Added  %7Bcourseid%7D and %7Buserid%7D

- CHANGELOG.md
- README.md
- filter.php
Naturally, these only work in a course and course completion must be enabled and configured in order for the {coursecompletiondate} tag  to work correctly.
> New tags: {coursestartdate}, {courseenddate}, {coursecompetiondate}

- CHANGELOG.md
- README.md
- filter.php
- version.php
... as an alternative to {sesskey} for use with encoded URLs.
> Added new %7Bsesskey%7D tag

- CHANGELOG.md
- README.md
- filter.php
- lang/en/filter_filtercodes.php
- version.php
Added new {lastname} tag
Added new {courseshortname} tag
Added new {scrape} tags.
Added new {sitedate} tag.
Added new {ifhome} tag (not ishome).
Added new {ifdashboard} tag.
Added new {coursecount} tag.
Added new {usersactive} tag.
Added new {usersonline} tag.
> New tags: lastname, courseshortname, scrape, sidedate, ifhome, ifdashboard, coursecount, usersactive, usersonline

- CHANGELOG.md
- README.md
- filter.php
Display visible custom profile fields.
> Added new {profile_field_[shortname]} tag.

- README.md
- filter.php
Added support for embedded FilterCodes in forms {form...} tags so that they process embedded FilterCode tags.
> Added support for embedded FilterCodes in forms {form...}

- CHANGELOG.md
- README.md
- filter.php
- tests/filter_test.php
Action URL for Contact Form forms. Requires Contact Form for Moodle.
> Added new {wwwcontactform} tag.

- .travis.yml
- CHANGELOG.md
- README.md
- composer.json
- db/upgrade.php
- filter.php
- settings.php
- tests/filter_test.php
Hi! we added a feature to get allow show messages by custom roles identified by roleid.
We added a feature to allow roles in course or not
Best regards
> Added custom roles

- CHANGELOG.md
- README.md
- filter.php
This displays the web page URL in the user's profile settings.
> Added new {webpage} tag.

- README.md
- filter.php
Hi @michael-milette this PR adds a new last login date filter code.
I've tested this on Moodle 3.9
> Add new last login date filter code

- CHANGELOG.md
- README.md
This is to address the issue reported in issue #231 .
> Fix 231: Updated documentation for {coursecards} tag.

- CHANGELOG.md
- settings/general.php
This PR addresses the issue described in #236
> Fix 236: Resolved Moodle installation bug.

- filter.php
- tests/filter_test.php
Fix for null parameter passed to trim()
> #269 Fix php 8.1 deprecation

- classes/text_filter.php
> Fix duplicate static variable mycohorts

- classes/text_filter.php
- settings/general.php
Hi,
I would like to offer the following patch with a few recommended changes.
I attempted to contact you via your website in late January, but having not heard back I decided to share this here.
Please let me know if you'd like to discuss these in more details.
Thanks!
Fred
> Recommendations with regards to button and sesskey
